- name:  "Ansible 2.9+ required"
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.9', '>=')
    msg: "Required Ansible version is 2.9+"

- name: "Debian 10 required"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version in [ "10" ]
    msg: "Only Debian 10 is supported, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

- name: "install sendmail package"
  package:
    name: sendmail
    state: present

- name: "install mailutils package"
  package:
    name: mailutils
    state: present

- name: "add docker0 bridge network to /etc/hosts to avoid warnings in log"
  when: ansible_facts.docker0 is defined
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_facts.docker0.ipv4.address }} docker0"

- name: "add {{ sendmail_for_docker_bridge_network_name }} bridge network gateway to /etc/hosts to avoid warnings in log"
  lineinfile:
    path: /etc/hosts
    line: "{{ sendmail_for_docker_bridge_network_gateway}} {{ sendmail_for_docker_bridge_network_name }}"

- name: "make sendmail to listen on all IP addresses"
  lineinfile:
    path: /etc/mail/sendmail.mc
    regexp: 'DAEMON_OPTIONS\(\`Family=inet,  Name=MTA-v4, Port=smtp,'
    line:   "DAEMON_OPTIONS(`Family=inet,  Name=MTA-v4, Port=smtp, Addr=0.0.0.0')dnl"
  register: smtp_ip_address

- name: "add lines to sendmail.mc (usually to set SMTP relay)"
  blockinfile:
    dest: /etc/mail/sendmail.mc
    insertbefore: '^MAILER_DEFINITIONS'
    marker: 'dnl # {mark} ANSIBLE MANAGED BLOCK'
    block: "{{ sendmail_for_docker_config }}"
  register: smtp_relay

- name: "allow relaying from docker subnet"
  blockinfile:
    dest: /etc/mail/access
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    block: |
      Connect:192.168 RELAY
      GreetPause:192.168 0
      ClientRate:192.168 0
      ClientConn:192.168 0
  register: smtp_subnet

- name: "rebuild sendmail files"
  when: smtp_ip_address.changed or smtp_relay.changed or smtp_subnet.changed
  command:
    chdir: /etc/mail
    cmd: "make"
  register: sendmail_reloaded

- name: "set hostname"
  hostname:
    name: "{{ sendmail_for_docker_hostname }}"

- name: "set /etc/hostname"
  copy:
    dest: /etc/hostname
    content: "{{ sendmail_for_docker_hostname }}"

- name: "reload sendmail service"
  when: sendmail_reloaded.changed
  service:
    name: sendmail
    state: restarted